/* Generated by re2c 2.2 on Tue Jan 25 19:09:35 2022 */
#line 1 "src/lexer.re.c"
static
int lex_name(TSLexer *lexer) {
#line 6 "src/lexer.c"
{
  int32_t yych;
  unsigned int yyaccept = 0;
  yych = YYPEEK;
  switch (yych) {
    case 0x00: goto yy2;
    case '\t':
    case '\n':
    case '\r':
    case ' ':
    case '#':
    case ':':
    case '=': goto yy6;
    case '$': goto yy7;
    case '%': goto yy8;
    case '-':
    case 's': goto yy9;
    case '.': goto yy10;
    case '\\': goto yy11;
    case 'd': goto yy12;
    case 'e': goto yy13;
    case 'i': goto yy14;
    case 'o': goto yy15;
    case 'p': goto yy16;
    case 'u': goto yy17;
    case 'v': goto yy18;
    default: goto yy4;
  }
yy2:
  YYSKIP;
#line 53 "src/lexer.re.c"
  { return EMPTY; }
#line 39 "src/lexer.c"
yy4:
  yyaccept = 0;
  YYSKIP;
  /* YYBACKUP */
  yych = YYPEEK;
  switch (yych) {
    case 0x00:
    case '\n':
    case '\r':
    case '#': goto yy5;
    default: goto yy20;
  }
yy5:
#line 52 "src/lexer.re.c"
  { return -2; }
#line 55 "src/lexer.c"
yy6:
  YYSKIP;
  goto yy5;
yy7:
  yyaccept = 0;
  YYSKIP;
  /* YYBACKUP */
  yych = YYPEEK;
  switch (yych) {
    case '#':
    case '$': goto yy5;
    case '(': goto yy32;
    case '{': goto yy34;
    default: goto yy19;
  }
yy8:
  yyaccept = 0;
  YYSKIP;
  /* YYBACKUP */
  yych = YYPEEK;
  switch (yych) {
    case 0x00:
    case '\n':
    case '\r':
    case '#': goto yy5;
    default: goto yy26;
  }
yy9:
  yyaccept = 0;
  YYSKIP;
  /* YYBACKUP */
  yych = YYPEEK;
  switch (yych) {
    case 0x00:
    case '\n':
    case '\r':
    case '#': goto yy5;
    case 'i': goto yy42;
    default: goto yy20;
  }
yy10:
  yyaccept = 0;
  YYSKIP;
  /* YYBACKUP */
  yych = YYPEEK;
  switch (yych) {
    case 0x00:
    case '\n':
    case '\r':
    case '#': goto yy5;
    case 'R': goto yy43;
    case 'S': goto yy44;
    default: goto yy20;
  }
yy11:
  yyaccept = 0;
  YYSKIP;
  /* YYBACKUP */
  yych = YYPEEK;
  switch (yych) {
    case 0x00:
    case '#': goto yy45;
    case '\t':
    case ' ': goto yy47;
    case '\n':
    case '\r': goto yy5;
    case '$': goto yy48;
    case ':': goto yy49;
    case '\\': goto yy50;
    default: goto yy20;
  }
yy12:
  yyaccept = 0;
  YYSKIP;
  /* YYBACKUP */
  yych = YYPEEK;
  switch (yych) {
    case 0x00:
    case '\n':
    case '\r':
    case '#': goto yy5;
    case 'e': goto yy51;
    default: goto yy20;
  }
yy13:
  yyaccept = 0;
  YYSKIP;
  /* YYBACKUP */
  yych = YYPEEK;
  switch (yych) {
    case 0x00:
    case '\n':
    case '\r':
    case '#': goto yy5;
    case 'n': goto yy52;
    case 'x': goto yy53;
    default: goto yy20;
  }
yy14:
  yyaccept = 0;
  YYSKIP;
  /* YYBACKUP */
  yych = YYPEEK;
  switch (yych) {
    case 0x00:
    case '\n':
    case '\r':
    case '#': goto yy5;
    case 'f': goto yy54;
    case 'n': goto yy55;
    default: goto yy20;
  }
yy15:
  yyaccept = 0;
  YYSKIP;
  /* YYBACKUP */
  yych = YYPEEK;
  switch (yych) {
    case 0x00:
    case '\n':
    case '\r':
    case '#': goto yy5;
    case 'v': goto yy56;
    default: goto yy20;
  }
yy16:
  yyaccept = 0;
  YYSKIP;
  /* YYBACKUP */
  yych = YYPEEK;
  switch (yych) {
    case 0x00:
    case '\n':
    case '\r':
    case '#': goto yy5;
    case 'r': goto yy57;
    default: goto yy20;
  }
yy17:
  yyaccept = 0;
  YYSKIP;
  /* YYBACKUP */
  yych = YYPEEK;
  switch (yych) {
    case 0x00:
    case '\n':
    case '\r':
    case '#': goto yy5;
    case 'n': goto yy58;
    default: goto yy20;
  }
yy18:
  yyaccept = 0;
  YYSKIP;
  /* YYBACKUP */
  yych = YYPEEK;
  switch (yych) {
    case 0x00:
    case '\n':
    case '\r':
    case '#': goto yy5;
    case 'p': goto yy59;
    default: goto yy20;
  }
yy19:
  YYSKIP;
  yych = YYPEEK;
yy20:
  switch (yych) {
    case 0x00:
    case '\n':
    case '\r':
    case '#': goto yy21;
    case '\t':
    case ' ': goto yy22;
    case '$': goto yy24;
    case '%': goto yy25;
    case ':': goto yy27;
    case '=': goto yy29;
    case '\\': goto yy31;
    default: goto yy19;
  }
yy21:
  /* YYRESTORE */
  switch (yyaccept) {
    case 0: goto yy5;
    case 1: goto yy28;
    case 2: goto yy40;
    default: goto yy149;
  }
yy22:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 0x00:
    case '\n':
    case '\r':
    case '#': goto yy21;
    case '\t':
    case ' ': goto yy22;
    case '!':
    case '+':
    case '?': goto yy60;
    case '$': goto yy61;
    case '%': goto yy62;
    case ':': goto yy27;
    case '=': goto yy29;
    case '\\': goto yy64;
    default: goto yy45;
  }
yy24:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case '#':
    case '$': goto yy21;
    case '(': goto yy32;
    case '{': goto yy34;
    default: goto yy19;
  }
yy25:
  YYSKIP;
  yych = YYPEEK;
yy26:
  switch (yych) {
    case 0x00:
    case '\n':
    case '\r':
    case '#': goto yy21;
    case '\t':
    case ' ': goto yy36;
    case '$': goto yy38;
    case ':': goto yy39;
    case '=': goto yy29;
    case '\\': goto yy41;
    default: goto yy25;
  }
yy27:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case ':': goto yy65;
    case '=': goto yy29;
    default: goto yy28;
  }
yy28:
#line 62 "src/lexer.re.c"
  { return FILENAME_SPEC; }
#line 304 "src/lexer.c"
yy29:
  YYSKIP;
#line 60 "src/lexer.re.c"
  { return ASSIGNMENT_MARK;     }
#line 309 "src/lexer.c"
yy31:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 0x00:
    case '#': goto yy45;
    case '\t':
    case ' ': goto yy47;
    case '\n': goto yy22;
    case '\r': goto yy66;
    case '$': goto yy48;
    case '%': goto yy25;
    case ':': goto yy67;
    case '=': goto yy29;
    case '\\': goto yy68;
    default: goto yy19;
  }
yy32:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case '\n':
    case '\r': goto yy21;
    case ')': goto yy19;
    default: goto yy32;
  }
yy34:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case '\n':
    case '\r': goto yy21;
    case '}': goto yy19;
    default: goto yy34;
  }
yy36:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 0x00:
    case '\n':
    case '\r':
    case '#': goto yy21;
    case '\t':
    case ' ': goto yy36;
    case '!':
    case '+':
    case '?': goto yy69;
    case '$': goto yy70;
    case ':': goto yy39;
    case '=': goto yy29;
    case '\\': goto yy71;
    default: goto yy62;
  }
yy38:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case '#':
    case '$': goto yy21;
    case '(': goto yy72;
    case '{': goto yy74;
    default: goto yy25;
  }
yy39:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case ':': goto yy76;
    case '=': goto yy29;
    default: goto yy40;
  }
yy40:
#line 63 "src/lexer.re.c"
  { return PATTERN_SPEC;  }
#line 385 "src/lexer.c"
yy41:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 0x00:
    case '#': goto yy62;
    case '\t':
    case ' ': goto yy77;
    case '\n': goto yy36;
    case '\r': goto yy78;
    case '$': goto yy48;
    case ':': goto yy79;
    case '=': goto yy29;
    case '\\': goto yy80;
    default: goto yy25;
  }
yy42:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 'n': goto yy55;
    default: goto yy20;
  }
yy43:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 'E': goto yy81;
    default: goto yy20;
  }
yy44:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 'E': goto yy82;
    default: goto yy20;
  }
yy45:
  YYSKIP;
  yych = YYPEEK;
yy46:
  switch (yych) {
    case 0x00:
    case '\n':
    case '\r':
    case '#':
    case '=': goto yy21;
    case '\t':
    case ' ': goto yy83;
    case '$': goto yy61;
    case '%': goto yy62;
    case ':': goto yy85;
    case '\\': goto yy86;
    default: goto yy45;
  }
yy47:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case '\t':
    case ' ': goto yy22;
    case '!':
    case '+':
    case '?': goto yy60;
    case ':': goto yy27;
    case '=': goto yy29;
    case '\\': goto yy87;
    default: goto yy46;
  }
yy48:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case '#':
    case '$': goto yy21;
    case '(': goto yy90;
    case '{': goto yy92;
    default: goto yy88;
  }
yy49:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case ':': goto yy94;
    case '=': goto yy29;
    default: goto yy46;
  }
yy50:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case '\n': goto yy95;
    case '\r': goto yy97;
    default: goto yy20;
  }
yy51:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 'f': goto yy98;
    default: goto yy20;
  }
yy52:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 'd': goto yy99;
    default: goto yy20;
  }
yy53:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 'p': goto yy100;
    default: goto yy20;
  }
yy54:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 'd': goto yy99;
    case 'n': goto yy52;
    default: goto yy20;
  }
yy55:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 'c': goto yy101;
    default: goto yy20;
  }
yy56:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 'e': goto yy102;
    default: goto yy20;
  }
yy57:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 'i': goto yy103;
    default: goto yy20;
  }
yy58:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 'd': goto yy104;
    case 'e': goto yy105;
    default: goto yy20;
  }
yy59:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 'a': goto yy106;
    default: goto yy20;
  }
yy60:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case '=': goto yy29;
    default: goto yy46;
  }
yy61:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case '#':
    case '$': goto yy21;
    case '(': goto yy107;
    case '{': goto yy109;
    default: goto yy45;
  }
yy62:
  YYSKIP;
  yych = YYPEEK;
yy63:
  switch (yych) {
    case 0x00:
    case '\n':
    case '\r':
    case '#':
    case '=': goto yy21;
    case '\t':
    case ' ': goto yy111;
    case '$': goto yy70;
    case ':': goto yy113;
    case '\\': goto yy114;
    default: goto yy62;
  }
yy64:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case '\n': goto yy22;
    case '\r': goto yy66;
    case '$':
    case '=': goto yy21;
    case '%': goto yy62;
    default: goto yy45;
  }
yy65:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case '=': goto yy29;
    default: goto yy28;
  }
yy66:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case '\n': goto yy22;
    default: goto yy21;
  }
yy67:
  yyaccept = 1;
  YYSKIP;
  /* YYBACKUP */
  yych = YYPEEK;
  switch (yych) {
    case 0x00:
    case '\n':
    case '\r':
    case '#': goto yy28;
    case ':': goto yy94;
    case '=': goto yy29;
    default: goto yy46;
  }
yy68:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 0x00:
    case '#': goto yy21;
    case '\t':
    case '\n':
    case ' ': goto yy22;
    case '\r': goto yy66;
    case '$': goto yy24;
    case '%': goto yy25;
    case ':': goto yy27;
    case '=': goto yy29;
    case '\\': goto yy31;
    default: goto yy19;
  }
yy69:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case '=': goto yy29;
    default: goto yy63;
  }
yy70:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case '#':
    case '$': goto yy21;
    case '(': goto yy115;
    case '{': goto yy117;
    default: goto yy62;
  }
yy71:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case '\n': goto yy36;
    case '\r': goto yy78;
    case '$':
    case '=': goto yy21;
    default: goto yy62;
  }
yy72:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case '\n':
    case '\r': goto yy21;
    case ')': goto yy25;
    default: goto yy72;
  }
yy74:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case '\n':
    case '\r': goto yy21;
    case '}': goto yy25;
    default: goto yy74;
  }
yy76:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case '=': goto yy29;
    default: goto yy40;
  }
yy77:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case '\t':
    case ' ': goto yy36;
    case '!':
    case '+':
    case '?': goto yy69;
    case ':': goto yy39;
    case '=': goto yy29;
    case '\\': goto yy119;
    default: goto yy63;
  }
yy78:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case '\n': goto yy36;
    default: goto yy21;
  }
yy79:
  yyaccept = 2;
  YYSKIP;
  /* YYBACKUP */
  yych = YYPEEK;
  switch (yych) {
    case 0x00:
    case '\n':
    case '\r':
    case '#': goto yy40;
    case ':': goto yy120;
    case '=': goto yy29;
    default: goto yy63;
  }
yy80:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 0x00:
    case '#': goto yy21;
    case '\t':
    case '\n':
    case ' ': goto yy36;
    case '\r': goto yy78;
    case '$': goto yy38;
    case ':': goto yy39;
    case '=': goto yy29;
    case '\\': goto yy41;
    default: goto yy25;
  }
yy81:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 'C': goto yy121;
    default: goto yy20;
  }
yy82:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 'C': goto yy122;
    default: goto yy20;
  }
yy83:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 0x00:
    case '\n':
    case '\r':
    case '#':
    case '=': goto yy21;
    case '\t':
    case ' ': goto yy83;
    case '$': goto yy61;
    case '%': goto yy62;
    case ':': goto yy85;
    case '\\': goto yy123;
    default: goto yy45;
  }
yy85:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case ':': goto yy124;
    default: goto yy28;
  }
yy86:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case '\n': goto yy83;
    case '\r': goto yy125;
    case '$':
    case '=': goto yy21;
    case '%': goto yy62;
    case ':': goto yy126;
    case '\\': goto yy127;
    default: goto yy45;
  }
yy87:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case '\n': goto yy22;
    case '\r': goto yy66;
    case '$':
    case '=': goto yy21;
    case '%': goto yy62;
    case ':': goto yy126;
    case '\\': goto yy127;
    default: goto yy45;
  }
yy88:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 0x00:
    case '\n':
    case '\r':
    case '#': goto yy21;
    case '\t':
    case ' ': goto yy95;
    case '$': goto yy48;
    case ':': goto yy128;
    case '=': goto yy29;
    case '\\': goto yy129;
    default: goto yy88;
  }
yy90:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case '\n':
    case '\r': goto yy21;
    case ')': goto yy88;
    default: goto yy90;
  }
yy92:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case '\n':
    case '\r': goto yy21;
    case '}': goto yy88;
    default: goto yy92;
  }
yy94:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case ':': goto yy124;
    case '=': goto yy29;
    default: goto yy28;
  }
yy95:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case '\t':
    case ' ': goto yy95;
    case '!':
    case '+':
    case '?': goto yy131;
    case ':': goto yy128;
    case '=': goto yy29;
    case '\\': goto yy132;
    default: goto yy21;
  }
yy97:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case '\n': goto yy95;
    default: goto yy21;
  }
yy98:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 'i': goto yy133;
    default: goto yy20;
  }
yy99:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 'e': goto yy134;
    default: goto yy20;
  }
yy100:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 'o': goto yy135;
    default: goto yy20;
  }
yy101:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 'l': goto yy136;
    default: goto yy20;
  }
yy102:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 'r': goto yy137;
    default: goto yy20;
  }
yy103:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 'v': goto yy138;
    default: goto yy20;
  }
yy104:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 'e': goto yy51;
    default: goto yy20;
  }
yy105:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 'x': goto yy53;
    default: goto yy20;
  }
yy106:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 't': goto yy139;
    default: goto yy20;
  }
yy107:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case '\n':
    case '\r': goto yy21;
    case ')': goto yy45;
    default: goto yy107;
  }
yy109:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case '\n':
    case '\r': goto yy21;
    case '}': goto yy45;
    default: goto yy109;
  }
yy111:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 0x00:
    case '\n':
    case '\r':
    case '#':
    case '=': goto yy21;
    case '\t':
    case ' ': goto yy111;
    case '$': goto yy70;
    case ':': goto yy113;
    case '\\': goto yy140;
    default: goto yy62;
  }
yy113:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case ':': goto yy141;
    default: goto yy40;
  }
yy114:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case '\n': goto yy111;
    case '\r': goto yy142;
    case '$':
    case '=': goto yy21;
    case ':': goto yy143;
    case '\\': goto yy144;
    default: goto yy62;
  }
yy115:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case '\n':
    case '\r': goto yy21;
    case ')': goto yy62;
    default: goto yy115;
  }
yy117:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case '\n':
    case '\r': goto yy21;
    case '}': goto yy62;
    default: goto yy117;
  }
yy119:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case '\n': goto yy36;
    case '\r': goto yy78;
    case '$':
    case '=': goto yy21;
    case ':': goto yy143;
    case '\\': goto yy144;
    default: goto yy62;
  }
yy120:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case ':': goto yy141;
    case '=': goto yy29;
    default: goto yy40;
  }
yy121:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 'I': goto yy145;
    default: goto yy20;
  }
yy122:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 'O': goto yy146;
    default: goto yy20;
  }
yy123:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case '\n': goto yy83;
    case '\r': goto yy125;
    case '$':
    case '=': goto yy21;
    case '%': goto yy62;
    default: goto yy45;
  }
yy124:
  YYSKIP;
  goto yy28;
yy125:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case '\n': goto yy83;
    default: goto yy21;
  }
yy126:
  yyaccept = 1;
  YYSKIP;
  /* YYBACKUP */
  yych = YYPEEK;
  switch (yych) {
    case 0x00:
    case '\n':
    case '\r':
    case '#':
    case '=': goto yy28;
    case '\t':
    case ' ': goto yy83;
    case '$': goto yy61;
    case '%': goto yy62;
    case ':': goto yy85;
    case '\\': goto yy86;
    default: goto yy45;
  }
yy127:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 0x00:
    case '#':
    case '=': goto yy21;
    case '\t':
    case '\n':
    case ' ': goto yy83;
    case '\r': goto yy125;
    case '$': goto yy61;
    case '%': goto yy62;
    case ':': goto yy85;
    case '\\': goto yy86;
    default: goto yy45;
  }
yy128:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case ':': goto yy131;
    case '=': goto yy29;
    default: goto yy21;
  }
yy129:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 0x00:
    case '#': goto yy21;
    case '\t':
    case '\n':
    case ' ': goto yy95;
    case '\r': goto yy97;
    case '$': goto yy48;
    case ':': goto yy128;
    case '=': goto yy29;
    case '\\': goto yy129;
    default: goto yy88;
  }
yy131:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case '=': goto yy29;
    default: goto yy21;
  }
yy132:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case '\n': goto yy95;
    case '\r': goto yy97;
    default: goto yy21;
  }
yy133:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 'n': goto yy147;
    default: goto yy20;
  }
yy134:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 'f': goto yy148;
    default: goto yy20;
  }
yy135:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 'r': goto yy150;
    default: goto yy20;
  }
yy136:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 'u': goto yy151;
    default: goto yy20;
  }
yy137:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 'r': goto yy152;
    default: goto yy20;
  }
yy138:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 'a': goto yy153;
    default: goto yy20;
  }
yy139:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 'h': goto yy148;
    default: goto yy20;
  }
yy140:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case '\n': goto yy111;
    case '\r': goto yy142;
    case '$':
    case '=': goto yy21;
    default: goto yy62;
  }
yy141:
  YYSKIP;
  goto yy40;
yy142:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case '\n': goto yy111;
    default: goto yy21;
  }
yy143:
  yyaccept = 2;
  YYSKIP;
  /* YYBACKUP */
  yych = YYPEEK;
  switch (yych) {
    case 0x00:
    case '\n':
    case '\r':
    case '#':
    case '=': goto yy40;
    case '\t':
    case ' ': goto yy111;
    case '$': goto yy70;
    case ':': goto yy113;
    case '\\': goto yy114;
    default: goto yy62;
  }
yy144:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 0x00:
    case '#':
    case '=': goto yy21;
    case '\t':
    case '\n':
    case ' ': goto yy111;
    case '\r': goto yy142;
    case '$': goto yy70;
    case ':': goto yy113;
    case '\\': goto yy114;
    default: goto yy62;
  }
yy145:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 'P': goto yy154;
    default: goto yy20;
  }
yy146:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 'N': goto yy155;
    default: goto yy20;
  }
yy147:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 'e': goto yy148;
    default: goto yy20;
  }
yy148:
  yyaccept = 3;
  YYSKIP;
  /* YYBACKUP */
  yych = YYPEEK;
  switch (yych) {
    case 0x00:
    case '\n':
    case '\r':
    case '#': goto yy149;
    case '\t':
    case ' ': goto yy156;
    case '\\': goto yy158;
    default: goto yy20;
  }
yy149:
#line 55 "src/lexer.re.c"
  { return DIRECTIVE; }
#line 1272 "src/lexer.c"
yy150:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 't': goto yy148;
    default: goto yy20;
  }
yy151:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 'd': goto yy147;
    default: goto yy20;
  }
yy152:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 'i': goto yy151;
    default: goto yy20;
  }
yy153:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 't': goto yy147;
    default: goto yy20;
  }
yy154:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 'E': goto yy159;
    default: goto yy20;
  }
yy155:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 'D': goto yy160;
    default: goto yy20;
  }
yy156:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 0x00:
    case '\n':
    case '\r': goto yy149;
    case '\t':
    case ' ': goto yy156;
    case '!':
    case '+':
    case '?': goto yy163;
    case '#': goto yy164;
    case '$': goto yy166;
    case '%': goto yy167;
    case ':': goto yy169;
    case '=': goto yy29;
    case '\\': goto yy170;
    default: goto yy161;
  }
yy158:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 0x00:
    case '#': goto yy45;
    case '\t':
    case ' ': goto yy47;
    case '\n': goto yy156;
    case '\r': goto yy171;
    case '$': goto yy48;
    case ':': goto yy67;
    case '\\': goto yy68;
    default: goto yy20;
  }
yy159:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 'P': goto yy172;
    default: goto yy20;
  }
yy160:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 'E': goto yy173;
    default: goto yy20;
  }
yy161:
  YYSKIP;
  yych = YYPEEK;
yy162:
  switch (yych) {
    case 0x00:
    case '\n':
    case '\r':
    case '=': goto yy149;
    case '\t':
    case ' ': goto yy174;
    case '#':
    case ':': goto yy164;
    case '$': goto yy166;
    case '%': goto yy167;
    case '\\': goto yy176;
    default: goto yy161;
  }
yy163:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case '=': goto yy29;
    default: goto yy162;
  }
yy164:
  YYSKIP;
  yych = YYPEEK;
yy165:
  switch (yych) {
    case 0x00:
    case '\n':
    case '\r':
    case '=': goto yy149;
    default: goto yy164;
  }
yy166:
  yyaccept = 3;
  YYSKIP;
  /* YYBACKUP */
  yych = YYPEEK;
  switch (yych) {
    case 0x00:
    case '\n':
    case '\r':
    case '=': goto yy45;
    case '#':
    case '$': goto yy164;
    case '(': goto yy177;
    case '{': goto yy179;
    default: goto yy161;
  }
yy167:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 0x00:
    case '\n':
    case '\r':
    case '=': goto yy149;
    case '\t':
    case ' ': goto yy181;
    case '#':
    case ':': goto yy164;
    case '$': goto yy183;
    case '\\': goto yy184;
    default: goto yy167;
  }
yy169:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case ':': goto yy185;
    case '=': goto yy29;
    default: goto yy165;
  }
yy170:
  yyaccept = 3;
  YYSKIP;
  /* YYBACKUP */
  yych = YYPEEK;
  switch (yych) {
    case 0x00: goto yy45;
    case '\n': goto yy156;
    case '\r': goto yy171;
    case '$': goto yy164;
    case '%': goto yy167;
    case '=': goto yy149;
    default: goto yy161;
  }
yy171:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case '\n': goto yy156;
    default: goto yy21;
  }
yy172:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 'R': goto yy186;
    default: goto yy20;
  }
yy173:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 'X': goto yy187;
    default: goto yy20;
  }
yy174:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 0x00:
    case '\n':
    case '\r':
    case '=': goto yy149;
    case '\t':
    case ' ': goto yy174;
    case '#':
    case ':': goto yy164;
    case '$': goto yy166;
    case '%': goto yy167;
    case '\\': goto yy188;
    default: goto yy161;
  }
yy176:
  yyaccept = 3;
  YYSKIP;
  /* YYBACKUP */
  yych = YYPEEK;
  switch (yych) {
    case 0x00: goto yy45;
    case '\n': goto yy83;
    case '\r': goto yy125;
    case '$': goto yy164;
    case '%': goto yy167;
    case '=': goto yy149;
    case '\\': goto yy189;
    default: goto yy161;
  }
yy177:
  yyaccept = 3;
  YYSKIP;
  /* YYBACKUP */
  yych = YYPEEK;
  switch (yych) {
    case 0x00:
    case '=': goto yy107;
    case '\n':
    case '\r': goto yy149;
    case ')': goto yy161;
    default: goto yy177;
  }
yy179:
  yyaccept = 3;
  YYSKIP;
  /* YYBACKUP */
  yych = YYPEEK;
  switch (yych) {
    case 0x00:
    case '=': goto yy109;
    case '\n':
    case '\r': goto yy149;
    case '}': goto yy161;
    default: goto yy179;
  }
yy181:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 0x00:
    case '\n':
    case '\r':
    case '=': goto yy149;
    case '\t':
    case ' ': goto yy181;
    case '#':
    case ':': goto yy164;
    case '$': goto yy183;
    case '\\': goto yy190;
    default: goto yy167;
  }
yy183:
  yyaccept = 3;
  YYSKIP;
  /* YYBACKUP */
  yych = YYPEEK;
  switch (yych) {
    case 0x00:
    case '\n':
    case '\r':
    case '=': goto yy62;
    case '#':
    case '$': goto yy164;
    case '(': goto yy191;
    case '{': goto yy193;
    default: goto yy167;
  }
yy184:
  yyaccept = 3;
  YYSKIP;
  /* YYBACKUP */
  yych = YYPEEK;
  switch (yych) {
    case 0x00: goto yy62;
    case '\n': goto yy111;
    case '\r': goto yy142;
    case '$': goto yy164;
    case '=': goto yy149;
    case '\\': goto yy195;
    default: goto yy167;
  }
yy185:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case '=': goto yy29;
    default: goto yy165;
  }
yy186:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 'E': goto yy196;
    default: goto yy20;
  }
yy187:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 'P': goto yy197;
    default: goto yy20;
  }
yy188:
  yyaccept = 3;
  YYSKIP;
  /* YYBACKUP */
  yych = YYPEEK;
  switch (yych) {
    case 0x00: goto yy45;
    case '\n': goto yy83;
    case '\r': goto yy125;
    case '$': goto yy164;
    case '%': goto yy167;
    case '=': goto yy149;
    default: goto yy161;
  }
yy189:
  yyaccept = 3;
  YYSKIP;
  /* YYBACKUP */
  yych = YYPEEK;
  switch (yych) {
    case 0x00:
    case '=': goto yy149;
    case '\t':
    case ' ': goto yy174;
    case '\n': goto yy83;
    case '\r': goto yy125;
    case '#':
    case ':': goto yy164;
    case '$': goto yy166;
    case '%': goto yy167;
    case '\\': goto yy176;
    default: goto yy161;
  }
yy190:
  yyaccept = 3;
  YYSKIP;
  /* YYBACKUP */
  yych = YYPEEK;
  switch (yych) {
    case 0x00: goto yy62;
    case '\n': goto yy111;
    case '\r': goto yy142;
    case '$': goto yy164;
    case '=': goto yy149;
    default: goto yy167;
  }
yy191:
  yyaccept = 3;
  YYSKIP;
  /* YYBACKUP */
  yych = YYPEEK;
  switch (yych) {
    case 0x00:
    case '=': goto yy115;
    case '\n':
    case '\r': goto yy149;
    case ')': goto yy167;
    default: goto yy191;
  }
yy193:
  yyaccept = 3;
  YYSKIP;
  /* YYBACKUP */
  yych = YYPEEK;
  switch (yych) {
    case 0x00:
    case '=': goto yy117;
    case '\n':
    case '\r': goto yy149;
    case '}': goto yy167;
    default: goto yy193;
  }
yy195:
  yyaccept = 3;
  YYSKIP;
  /* YYBACKUP */
  yych = YYPEEK;
  switch (yych) {
    case 0x00:
    case '=': goto yy149;
    case '\t':
    case ' ': goto yy181;
    case '\n': goto yy111;
    case '\r': goto yy142;
    case '#':
    case ':': goto yy164;
    case '$': goto yy183;
    case '\\': goto yy184;
    default: goto yy167;
  }
yy196:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 'F': goto yy198;
    default: goto yy20;
  }
yy197:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 'A': goto yy199;
    default: goto yy20;
  }
yy198:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 'I': goto yy200;
    default: goto yy20;
  }
yy199:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 'N': goto yy201;
    default: goto yy20;
  }
yy200:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 'X': goto yy202;
    default: goto yy20;
  }
yy201:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 'S': goto yy203;
    default: goto yy20;
  }
yy202:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case '\t':
    case ' ': goto yy204;
    case '!':
    case '+':
    case '?': goto yy206;
    case ':': goto yy207;
    case '=': goto yy208;
    case '\\': goto yy210;
    default: goto yy20;
  }
yy203:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 'I': goto yy211;
    default: goto yy20;
  }
yy204:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 0x00:
    case '\n':
    case '\r':
    case '#': goto yy21;
    case '\t':
    case ' ': goto yy204;
    case '!':
    case '+':
    case '?': goto yy212;
    case '$': goto yy61;
    case '%': goto yy62;
    case ':': goto yy207;
    case '=': goto yy208;
    case '\\': goto yy213;
    default: goto yy45;
  }
yy206:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case '=': goto yy208;
    default: goto yy20;
  }
yy207:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case ':': goto yy214;
    case '=': goto yy208;
    default: goto yy28;
  }
yy208:
  YYSKIP;
#line 58 "src/lexer.re.c"
  { return RECIPEPREFIX_VAR;    }
#line 1792 "src/lexer.c"
yy210:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 0x00:
    case '#': goto yy45;
    case '\t':
    case ' ': goto yy47;
    case '\n': goto yy204;
    case '\r': goto yy215;
    case '$': goto yy48;
    case ':': goto yy67;
    case '\\': goto yy68;
    default: goto yy20;
  }
yy211:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 'O': goto yy216;
    default: goto yy20;
  }
yy212:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case '=': goto yy208;
    default: goto yy46;
  }
yy213:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case '\n': goto yy204;
    case '\r': goto yy215;
    case '$':
    case '=': goto yy21;
    case '%': goto yy62;
    default: goto yy45;
  }
yy214:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case '=': goto yy208;
    default: goto yy28;
  }
yy215:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case '\n': goto yy204;
    default: goto yy21;
  }
yy216:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 'N': goto yy217;
    default: goto yy20;
  }
yy217:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case '\t':
    case ' ': goto yy218;
    case '!':
    case '+':
    case '?': goto yy220;
    case ':': goto yy221;
    case '=': goto yy222;
    case '\\': goto yy224;
    default: goto yy20;
  }
yy218:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 0x00:
    case '\n':
    case '\r':
    case '#': goto yy21;
    case '\t':
    case ' ': goto yy218;
    case '!':
    case '+':
    case '?': goto yy225;
    case '$': goto yy61;
    case '%': goto yy62;
    case ':': goto yy221;
    case '=': goto yy222;
    case '\\': goto yy226;
    default: goto yy45;
  }
yy220:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case '=': goto yy222;
    default: goto yy20;
  }
yy221:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case ':': goto yy227;
    case '=': goto yy222;
    default: goto yy28;
  }
yy222:
  YYSKIP;
#line 59 "src/lexer.re.c"
  { return SECONDEXPANSION_VAR; }
#line 1907 "src/lexer.c"
yy224:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 0x00:
    case '#': goto yy45;
    case '\t':
    case ' ': goto yy47;
    case '\n': goto yy218;
    case '\r': goto yy228;
    case '$': goto yy48;
    case ':': goto yy67;
    case '\\': goto yy68;
    default: goto yy20;
  }
yy225:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case '=': goto yy222;
    default: goto yy46;
  }
yy226:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case '\n': goto yy218;
    case '\r': goto yy228;
    case '$':
    case '=': goto yy21;
    case '%': goto yy62;
    default: goto yy45;
  }
yy227:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case '=': goto yy222;
    default: goto yy28;
  }
yy228:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case '\n': goto yy218;
    default: goto yy21;
  }
}
#line 65 "src/lexer.re.c"
}
