/* Generated by re2c 2.2 on Thu Jan 27 23:47:56 2022 */
#line 1 "src/lexer.re.c"
static
int lex_name(TSLexer *lexer) {
#line 6 "src/lexer.c"
{
  int32_t yych;
  unsigned int yyaccept = 0;
  yych = YYPEEK;
  switch (yych) {
    case 0x00: goto yy2;
    case '\t':
    case '\n':
    case '\r':
    case ' ':
    case '#':
    case ':':
    case '=': goto yy6;
    case '$': goto yy7;
    case '%': goto yy8;
    case '-':
    case 's': goto yy9;
    case '.': goto yy10;
    case '\\': goto yy11;
    case 'd': goto yy12;
    case 'e': goto yy13;
    case 'i': goto yy14;
    case 'o': goto yy15;
    case 'p': goto yy16;
    case 'u': goto yy17;
    case 'v': goto yy18;
    default: goto yy4;
  }
yy2:
  YYSKIP;
#line 51 "src/lexer.re.c"
  { return EMPTY; }
#line 39 "src/lexer.c"
yy4:
  yyaccept = 0;
  YYSKIP;
  /* YYBACKUP */
  yych = YYPEEK;
  switch (yych) {
    case 0x00:
    case '\n':
    case '\r':
    case '#': goto yy5;
    default: goto yy20;
  }
yy5:
#line 50 "src/lexer.re.c"
  { return -2; }
#line 55 "src/lexer.c"
yy6:
  YYSKIP;
  goto yy5;
yy7:
  yyaccept = 0;
  YYSKIP;
  /* YYBACKUP */
  yych = YYPEEK;
  switch (yych) {
    case '#': goto yy5;
    case '$': goto yy32;
    case '(': goto yy33;
    case '{': goto yy35;
    default: goto yy19;
  }
yy8:
  yyaccept = 0;
  YYSKIP;
  /* YYBACKUP */
  yych = YYPEEK;
  switch (yych) {
    case 0x00:
    case '\n':
    case '\r':
    case '#': goto yy5;
    default: goto yy26;
  }
yy9:
  yyaccept = 0;
  YYSKIP;
  /* YYBACKUP */
  yych = YYPEEK;
  switch (yych) {
    case 0x00:
    case '\n':
    case '\r':
    case '#': goto yy5;
    case 'i': goto yy43;
    default: goto yy20;
  }
yy10:
  yyaccept = 0;
  YYSKIP;
  /* YYBACKUP */
  yych = YYPEEK;
  switch (yych) {
    case 0x00:
    case '\n':
    case '\r':
    case '#': goto yy5;
    case 'R': goto yy44;
    case 'S': goto yy45;
    default: goto yy20;
  }
yy11:
  yyaccept = 0;
  YYSKIP;
  /* YYBACKUP */
  yych = YYPEEK;
  switch (yych) {
    case 0x00:
    case '#': goto yy46;
    case '\t':
    case ' ': goto yy48;
    case '\n':
    case '\r': goto yy5;
    case '$': goto yy49;
    case ':': goto yy50;
    case '\\': goto yy51;
    default: goto yy20;
  }
yy12:
  yyaccept = 0;
  YYSKIP;
  /* YYBACKUP */
  yych = YYPEEK;
  switch (yych) {
    case 0x00:
    case '\n':
    case '\r':
    case '#': goto yy5;
    case 'e': goto yy52;
    default: goto yy20;
  }
yy13:
  yyaccept = 0;
  YYSKIP;
  /* YYBACKUP */
  yych = YYPEEK;
  switch (yych) {
    case 0x00:
    case '\n':
    case '\r':
    case '#': goto yy5;
    case 'n': goto yy53;
    case 'x': goto yy54;
    default: goto yy20;
  }
yy14:
  yyaccept = 0;
  YYSKIP;
  /* YYBACKUP */
  yych = YYPEEK;
  switch (yych) {
    case 0x00:
    case '\n':
    case '\r':
    case '#': goto yy5;
    case 'f': goto yy55;
    case 'n': goto yy56;
    default: goto yy20;
  }
yy15:
  yyaccept = 0;
  YYSKIP;
  /* YYBACKUP */
  yych = YYPEEK;
  switch (yych) {
    case 0x00:
    case '\n':
    case '\r':
    case '#': goto yy5;
    case 'v': goto yy57;
    default: goto yy20;
  }
yy16:
  yyaccept = 0;
  YYSKIP;
  /* YYBACKUP */
  yych = YYPEEK;
  switch (yych) {
    case 0x00:
    case '\n':
    case '\r':
    case '#': goto yy5;
    case 'r': goto yy58;
    default: goto yy20;
  }
yy17:
  yyaccept = 0;
  YYSKIP;
  /* YYBACKUP */
  yych = YYPEEK;
  switch (yych) {
    case 0x00:
    case '\n':
    case '\r':
    case '#': goto yy5;
    case 'n': goto yy59;
    default: goto yy20;
  }
yy18:
  yyaccept = 0;
  YYSKIP;
  /* YYBACKUP */
  yych = YYPEEK;
  switch (yych) {
    case 0x00:
    case '\n':
    case '\r':
    case '#': goto yy5;
    case 'p': goto yy60;
    default: goto yy20;
  }
yy19:
  YYSKIP;
  yych = YYPEEK;
yy20:
  switch (yych) {
    case 0x00:
    case '\n':
    case '\r':
    case '#': goto yy21;
    case '\t':
    case ' ': goto yy22;
    case '$': goto yy24;
    case '%': goto yy25;
    case ':': goto yy27;
    case '=': goto yy29;
    case '\\': goto yy31;
    default: goto yy19;
  }
yy21:
  /* YYRESTORE */
  switch (yyaccept) {
    case 0: goto yy5;
    case 1: goto yy28;
    case 2: goto yy41;
    case 3: goto yy154;
    case 4: goto yy229;
    default: goto yy253;
  }
yy22:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 0x00:
    case '\n':
    case '\r':
    case '#': goto yy21;
    case '\t':
    case ' ': goto yy22;
    case '!':
    case '+':
    case '?': goto yy61;
    case '$': goto yy62;
    case '%': goto yy63;
    case ':': goto yy27;
    case '=': goto yy29;
    case '\\': goto yy65;
    default: goto yy46;
  }
yy24:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case '#': goto yy21;
    case '$': goto yy32;
    case '(': goto yy33;
    case '{': goto yy35;
    default: goto yy19;
  }
yy25:
  YYSKIP;
  yych = YYPEEK;
yy26:
  switch (yych) {
    case 0x00:
    case '\n':
    case '\r':
    case '#': goto yy21;
    case '\t':
    case ' ': goto yy37;
    case '$': goto yy39;
    case ':': goto yy40;
    case '=': goto yy29;
    case '\\': goto yy42;
    default: goto yy25;
  }
yy27:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case ':': goto yy66;
    case '=': goto yy29;
    default: goto yy28;
  }
yy28:
#line 61 "src/lexer.re.c"
  { return FILENAME_SPEC; }
#line 306 "src/lexer.c"
yy29:
  YYSKIP;
#line 57 "src/lexer.re.c"
  { return ASSIGNMENT_MARK;     }
#line 311 "src/lexer.c"
yy31:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 0x00:
    case '#': goto yy46;
    case '\t':
    case ' ': goto yy48;
    case '\n': goto yy22;
    case '\r': goto yy67;
    case '$': goto yy49;
    case '%': goto yy25;
    case ':': goto yy68;
    case '=': goto yy29;
    case '\\': goto yy69;
    default: goto yy19;
  }
yy32:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case '#':
    case '$': goto yy21;
    case '(': goto yy33;
    case '{': goto yy35;
    default: goto yy19;
  }
yy33:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case '\n':
    case '\r': goto yy21;
    case ')': goto yy19;
    default: goto yy33;
  }
yy35:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case '\n':
    case '\r': goto yy21;
    case '}': goto yy19;
    default: goto yy35;
  }
yy37:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 0x00:
    case '\n':
    case '\r':
    case '#': goto yy21;
    case '\t':
    case ' ': goto yy37;
    case '!':
    case '+':
    case '?': goto yy70;
    case '$': goto yy71;
    case ':': goto yy40;
    case '=': goto yy29;
    case '\\': goto yy72;
    default: goto yy63;
  }
yy39:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case '#': goto yy21;
    case '$': goto yy73;
    case '(': goto yy74;
    case '{': goto yy76;
    default: goto yy25;
  }
yy40:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case ':': goto yy78;
    case '=': goto yy29;
    default: goto yy41;
  }
yy41:
#line 62 "src/lexer.re.c"
  { return PATTERN_SPEC;  }
#line 397 "src/lexer.c"
yy42:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 0x00:
    case '#': goto yy63;
    case '\t':
    case ' ': goto yy79;
    case '\n': goto yy37;
    case '\r': goto yy80;
    case '$': goto yy49;
    case ':': goto yy81;
    case '=': goto yy29;
    case '\\': goto yy82;
    default: goto yy25;
  }
yy43:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 'n': goto yy56;
    default: goto yy20;
  }
yy44:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 'E': goto yy83;
    default: goto yy20;
  }
yy45:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 'E': goto yy84;
    default: goto yy20;
  }
yy46:
  YYSKIP;
  yych = YYPEEK;
yy47:
  switch (yych) {
    case 0x00:
    case '\n':
    case '\r':
    case '#':
    case '=': goto yy21;
    case '\t':
    case ' ': goto yy85;
    case '$': goto yy62;
    case '%': goto yy63;
    case ':': goto yy87;
    case '\\': goto yy88;
    default: goto yy46;
  }
yy48:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case '\t':
    case ' ': goto yy22;
    case '!':
    case '+':
    case '?': goto yy61;
    case ':': goto yy27;
    case '=': goto yy29;
    case '\\': goto yy89;
    default: goto yy47;
  }
yy49:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case '#': goto yy21;
    case '$': goto yy92;
    case '(': goto yy93;
    case '{': goto yy95;
    default: goto yy90;
  }
yy50:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case ':': goto yy97;
    case '=': goto yy29;
    default: goto yy47;
  }
yy51:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case '\n': goto yy98;
    case '\r': goto yy100;
    default: goto yy20;
  }
yy52:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 'f': goto yy101;
    default: goto yy20;
  }
yy53:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 'd': goto yy102;
    default: goto yy20;
  }
yy54:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 'p': goto yy103;
    default: goto yy20;
  }
yy55:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 'd': goto yy102;
    case 'n': goto yy53;
    default: goto yy20;
  }
yy56:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 'c': goto yy104;
    default: goto yy20;
  }
yy57:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 'e': goto yy105;
    default: goto yy20;
  }
yy58:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 'i': goto yy106;
    default: goto yy20;
  }
yy59:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 'd': goto yy107;
    case 'e': goto yy108;
    default: goto yy20;
  }
yy60:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 'a': goto yy109;
    default: goto yy20;
  }
yy61:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case '=': goto yy29;
    default: goto yy47;
  }
yy62:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case '#': goto yy21;
    case '$': goto yy110;
    case '(': goto yy111;
    case '{': goto yy113;
    default: goto yy46;
  }
yy63:
  YYSKIP;
  yych = YYPEEK;
yy64:
  switch (yych) {
    case 0x00:
    case '\n':
    case '\r':
    case '#':
    case '=': goto yy21;
    case '\t':
    case ' ': goto yy115;
    case '$': goto yy71;
    case ':': goto yy117;
    case '\\': goto yy118;
    default: goto yy63;
  }
yy65:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case '\n': goto yy22;
    case '\r': goto yy67;
    case '$':
    case '=': goto yy21;
    case '%': goto yy63;
    default: goto yy46;
  }
yy66:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case '=': goto yy29;
    default: goto yy28;
  }
yy67:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case '\n': goto yy22;
    default: goto yy21;
  }
yy68:
  yyaccept = 1;
  YYSKIP;
  /* YYBACKUP */
  yych = YYPEEK;
  switch (yych) {
    case 0x00:
    case '\n':
    case '\r':
    case '#': goto yy28;
    case ':': goto yy97;
    case '=': goto yy29;
    default: goto yy47;
  }
yy69:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 0x00:
    case '#': goto yy21;
    case '\t':
    case '\n':
    case ' ': goto yy22;
    case '\r': goto yy67;
    case '$': goto yy24;
    case '%': goto yy25;
    case ':': goto yy27;
    case '=': goto yy29;
    case '\\': goto yy31;
    default: goto yy19;
  }
yy70:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case '=': goto yy29;
    default: goto yy64;
  }
yy71:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case '#': goto yy21;
    case '$': goto yy119;
    case '(': goto yy120;
    case '{': goto yy122;
    default: goto yy63;
  }
yy72:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case '\n': goto yy37;
    case '\r': goto yy80;
    case '$':
    case '=': goto yy21;
    default: goto yy63;
  }
yy73:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case '#':
    case '$': goto yy21;
    case '(': goto yy74;
    case '{': goto yy76;
    default: goto yy25;
  }
yy74:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case '\n':
    case '\r': goto yy21;
    case ')': goto yy25;
    default: goto yy74;
  }
yy76:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case '\n':
    case '\r': goto yy21;
    case '}': goto yy25;
    default: goto yy76;
  }
yy78:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case '=': goto yy29;
    default: goto yy41;
  }
yy79:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case '\t':
    case ' ': goto yy37;
    case '!':
    case '+':
    case '?': goto yy70;
    case ':': goto yy40;
    case '=': goto yy29;
    case '\\': goto yy124;
    default: goto yy64;
  }
yy80:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case '\n': goto yy37;
    default: goto yy21;
  }
yy81:
  yyaccept = 2;
  YYSKIP;
  /* YYBACKUP */
  yych = YYPEEK;
  switch (yych) {
    case 0x00:
    case '\n':
    case '\r':
    case '#': goto yy41;
    case ':': goto yy125;
    case '=': goto yy29;
    default: goto yy64;
  }
yy82:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 0x00:
    case '#': goto yy21;
    case '\t':
    case '\n':
    case ' ': goto yy37;
    case '\r': goto yy80;
    case '$': goto yy39;
    case ':': goto yy40;
    case '=': goto yy29;
    case '\\': goto yy42;
    default: goto yy25;
  }
yy83:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 'C': goto yy126;
    default: goto yy20;
  }
yy84:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 'C': goto yy127;
    default: goto yy20;
  }
yy85:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 0x00:
    case '\n':
    case '\r':
    case '#':
    case '=': goto yy21;
    case '\t':
    case ' ': goto yy85;
    case '$': goto yy62;
    case '%': goto yy63;
    case ':': goto yy87;
    case '\\': goto yy128;
    default: goto yy46;
  }
yy87:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case ':': goto yy129;
    default: goto yy28;
  }
yy88:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case '\n': goto yy85;
    case '\r': goto yy130;
    case '$':
    case '=': goto yy21;
    case '%': goto yy63;
    case ':': goto yy131;
    case '\\': goto yy132;
    default: goto yy46;
  }
yy89:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case '\n': goto yy22;
    case '\r': goto yy67;
    case '$':
    case '=': goto yy21;
    case '%': goto yy63;
    case ':': goto yy131;
    case '\\': goto yy132;
    default: goto yy46;
  }
yy90:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 0x00:
    case '\n':
    case '\r':
    case '#': goto yy21;
    case '\t':
    case ' ': goto yy98;
    case '$': goto yy49;
    case ':': goto yy133;
    case '=': goto yy29;
    case '\\': goto yy134;
    default: goto yy90;
  }
yy92:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case '#':
    case '$': goto yy21;
    case '(': goto yy93;
    case '{': goto yy95;
    default: goto yy90;
  }
yy93:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case '\n':
    case '\r': goto yy21;
    case ')': goto yy90;
    default: goto yy93;
  }
yy95:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case '\n':
    case '\r': goto yy21;
    case '}': goto yy90;
    default: goto yy95;
  }
yy97:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case ':': goto yy129;
    case '=': goto yy29;
    default: goto yy28;
  }
yy98:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case '\t':
    case ' ': goto yy98;
    case '!':
    case '+':
    case '?': goto yy136;
    case ':': goto yy133;
    case '=': goto yy29;
    case '\\': goto yy137;
    default: goto yy21;
  }
yy100:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case '\n': goto yy98;
    default: goto yy21;
  }
yy101:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 'i': goto yy138;
    default: goto yy20;
  }
yy102:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 'e': goto yy139;
    default: goto yy20;
  }
yy103:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 'o': goto yy140;
    default: goto yy20;
  }
yy104:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 'l': goto yy141;
    default: goto yy20;
  }
yy105:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 'r': goto yy142;
    default: goto yy20;
  }
yy106:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 'v': goto yy143;
    default: goto yy20;
  }
yy107:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 'e': goto yy52;
    default: goto yy20;
  }
yy108:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 'x': goto yy54;
    default: goto yy20;
  }
yy109:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 't': goto yy144;
    default: goto yy20;
  }
yy110:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case '#':
    case '$': goto yy21;
    case '(': goto yy111;
    case '{': goto yy113;
    default: goto yy46;
  }
yy111:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case '\n':
    case '\r': goto yy21;
    case ')': goto yy46;
    default: goto yy111;
  }
yy113:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case '\n':
    case '\r': goto yy21;
    case '}': goto yy46;
    default: goto yy113;
  }
yy115:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 0x00:
    case '\n':
    case '\r':
    case '#':
    case '=': goto yy21;
    case '\t':
    case ' ': goto yy115;
    case '$': goto yy71;
    case ':': goto yy117;
    case '\\': goto yy145;
    default: goto yy63;
  }
yy117:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case ':': goto yy146;
    default: goto yy41;
  }
yy118:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case '\n': goto yy115;
    case '\r': goto yy147;
    case '$':
    case '=': goto yy21;
    case ':': goto yy148;
    case '\\': goto yy149;
    default: goto yy63;
  }
yy119:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case '#':
    case '$': goto yy21;
    case '(': goto yy120;
    case '{': goto yy122;
    default: goto yy63;
  }
yy120:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case '\n':
    case '\r': goto yy21;
    case ')': goto yy63;
    default: goto yy120;
  }
yy122:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case '\n':
    case '\r': goto yy21;
    case '}': goto yy63;
    default: goto yy122;
  }
yy124:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case '\n': goto yy37;
    case '\r': goto yy80;
    case '$':
    case '=': goto yy21;
    case ':': goto yy148;
    case '\\': goto yy149;
    default: goto yy63;
  }
yy125:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case ':': goto yy146;
    case '=': goto yy29;
    default: goto yy41;
  }
yy126:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 'I': goto yy150;
    default: goto yy20;
  }
yy127:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 'O': goto yy151;
    default: goto yy20;
  }
yy128:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case '\n': goto yy85;
    case '\r': goto yy130;
    case '$':
    case '=': goto yy21;
    case '%': goto yy63;
    default: goto yy46;
  }
yy129:
  YYSKIP;
  goto yy28;
yy130:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case '\n': goto yy85;
    default: goto yy21;
  }
yy131:
  yyaccept = 1;
  YYSKIP;
  /* YYBACKUP */
  yych = YYPEEK;
  switch (yych) {
    case 0x00:
    case '\n':
    case '\r':
    case '#':
    case '=': goto yy28;
    case '\t':
    case ' ': goto yy85;
    case '$': goto yy62;
    case '%': goto yy63;
    case ':': goto yy87;
    case '\\': goto yy88;
    default: goto yy46;
  }
yy132:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 0x00:
    case '#':
    case '=': goto yy21;
    case '\t':
    case '\n':
    case ' ': goto yy85;
    case '\r': goto yy130;
    case '$': goto yy62;
    case '%': goto yy63;
    case ':': goto yy87;
    case '\\': goto yy88;
    default: goto yy46;
  }
yy133:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case ':': goto yy136;
    case '=': goto yy29;
    default: goto yy21;
  }
yy134:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 0x00:
    case '#': goto yy21;
    case '\t':
    case '\n':
    case ' ': goto yy98;
    case '\r': goto yy100;
    case '$': goto yy49;
    case ':': goto yy133;
    case '=': goto yy29;
    case '\\': goto yy134;
    default: goto yy90;
  }
yy136:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case '=': goto yy29;
    default: goto yy21;
  }
yy137:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case '\n': goto yy98;
    case '\r': goto yy100;
    default: goto yy21;
  }
yy138:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 'n': goto yy152;
    default: goto yy20;
  }
yy139:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 'f': goto yy153;
    default: goto yy20;
  }
yy140:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 'r': goto yy155;
    default: goto yy20;
  }
yy141:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 'u': goto yy156;
    default: goto yy20;
  }
yy142:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 'r': goto yy157;
    default: goto yy20;
  }
yy143:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 'a': goto yy158;
    default: goto yy20;
  }
yy144:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 'h': goto yy153;
    default: goto yy20;
  }
yy145:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case '\n': goto yy115;
    case '\r': goto yy147;
    case '$':
    case '=': goto yy21;
    default: goto yy63;
  }
yy146:
  YYSKIP;
  goto yy41;
yy147:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case '\n': goto yy115;
    default: goto yy21;
  }
yy148:
  yyaccept = 2;
  YYSKIP;
  /* YYBACKUP */
  yych = YYPEEK;
  switch (yych) {
    case 0x00:
    case '\n':
    case '\r':
    case '#':
    case '=': goto yy41;
    case '\t':
    case ' ': goto yy115;
    case '$': goto yy71;
    case ':': goto yy117;
    case '\\': goto yy118;
    default: goto yy63;
  }
yy149:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 0x00:
    case '#':
    case '=': goto yy21;
    case '\t':
    case '\n':
    case ' ': goto yy115;
    case '\r': goto yy147;
    case '$': goto yy71;
    case ':': goto yy117;
    case '\\': goto yy118;
    default: goto yy63;
  }
yy150:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 'P': goto yy159;
    default: goto yy20;
  }
yy151:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 'N': goto yy160;
    default: goto yy20;
  }
yy152:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 'e': goto yy153;
    default: goto yy20;
  }
yy153:
  yyaccept = 3;
  YYSKIP;
  /* YYBACKUP */
  yych = YYPEEK;
  switch (yych) {
    case 0x00:
    case '\n':
    case '\r':
    case '#': goto yy154;
    case '\t':
    case ' ': goto yy161;
    case '\\': goto yy163;
    default: goto yy20;
  }
yy154:
#line 53 "src/lexer.re.c"
  { return DIRECTIVE; }
#line 1324 "src/lexer.c"
yy155:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 't': goto yy153;
    default: goto yy20;
  }
yy156:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 'd': goto yy152;
    default: goto yy20;
  }
yy157:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 'i': goto yy156;
    default: goto yy20;
  }
yy158:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 't': goto yy152;
    default: goto yy20;
  }
yy159:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 'E': goto yy164;
    default: goto yy20;
  }
yy160:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 'D': goto yy165;
    default: goto yy20;
  }
yy161:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 0x00:
    case '\n':
    case '\r': goto yy154;
    case '\t':
    case ' ': goto yy161;
    case '!':
    case '+':
    case '?': goto yy168;
    case '#': goto yy169;
    case '$': goto yy171;
    case '%': goto yy172;
    case ':': goto yy174;
    case '=': goto yy29;
    case '\\': goto yy175;
    default: goto yy166;
  }
yy163:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 0x00:
    case '#': goto yy46;
    case '\t':
    case ' ': goto yy48;
    case '\n': goto yy161;
    case '\r': goto yy176;
    case '$': goto yy49;
    case ':': goto yy68;
    case '\\': goto yy69;
    default: goto yy20;
  }
yy164:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 'P': goto yy177;
    default: goto yy20;
  }
yy165:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 'E': goto yy178;
    default: goto yy20;
  }
yy166:
  YYSKIP;
  yych = YYPEEK;
yy167:
  switch (yych) {
    case 0x00:
    case '\n':
    case '\r':
    case '=': goto yy154;
    case '\t':
    case ' ': goto yy179;
    case '#':
    case ':': goto yy169;
    case '$': goto yy171;
    case '%': goto yy172;
    case '\\': goto yy181;
    default: goto yy166;
  }
yy168:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case '=': goto yy29;
    default: goto yy167;
  }
yy169:
  YYSKIP;
  yych = YYPEEK;
yy170:
  switch (yych) {
    case 0x00:
    case '\n':
    case '\r':
    case '=': goto yy154;
    default: goto yy169;
  }
yy171:
  yyaccept = 3;
  YYSKIP;
  /* YYBACKUP */
  yych = YYPEEK;
  switch (yych) {
    case 0x00:
    case '\n':
    case '\r':
    case '=': goto yy46;
    case '#': goto yy169;
    case '$': goto yy182;
    case '(': goto yy183;
    case '{': goto yy185;
    default: goto yy166;
  }
yy172:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 0x00:
    case '\n':
    case '\r':
    case '=': goto yy154;
    case '\t':
    case ' ': goto yy187;
    case '#':
    case ':': goto yy169;
    case '$': goto yy189;
    case '\\': goto yy190;
    default: goto yy172;
  }
yy174:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case ':': goto yy191;
    case '=': goto yy29;
    default: goto yy170;
  }
yy175:
  yyaccept = 3;
  YYSKIP;
  /* YYBACKUP */
  yych = YYPEEK;
  switch (yych) {
    case 0x00: goto yy46;
    case '\n': goto yy161;
    case '\r': goto yy176;
    case '$': goto yy169;
    case '%': goto yy172;
    case '=': goto yy154;
    default: goto yy166;
  }
yy176:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case '\n': goto yy161;
    default: goto yy21;
  }
yy177:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 'R': goto yy192;
    default: goto yy20;
  }
yy178:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 'X': goto yy193;
    default: goto yy20;
  }
yy179:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 0x00:
    case '\n':
    case '\r':
    case '=': goto yy154;
    case '\t':
    case ' ': goto yy179;
    case '#':
    case ':': goto yy169;
    case '$': goto yy171;
    case '%': goto yy172;
    case '\\': goto yy194;
    default: goto yy166;
  }
yy181:
  yyaccept = 3;
  YYSKIP;
  /* YYBACKUP */
  yych = YYPEEK;
  switch (yych) {
    case 0x00: goto yy46;
    case '\n': goto yy85;
    case '\r': goto yy130;
    case '$': goto yy169;
    case '%': goto yy172;
    case '=': goto yy154;
    case '\\': goto yy195;
    default: goto yy166;
  }
yy182:
  yyaccept = 3;
  YYSKIP;
  /* YYBACKUP */
  yych = YYPEEK;
  switch (yych) {
    case 0x00:
    case '\n':
    case '\r':
    case '=': goto yy46;
    case '#':
    case '$': goto yy169;
    case '(': goto yy183;
    case '{': goto yy185;
    default: goto yy166;
  }
yy183:
  yyaccept = 3;
  YYSKIP;
  /* YYBACKUP */
  yych = YYPEEK;
  switch (yych) {
    case 0x00:
    case '=': goto yy111;
    case '\n':
    case '\r': goto yy154;
    case ')': goto yy166;
    default: goto yy183;
  }
yy185:
  yyaccept = 3;
  YYSKIP;
  /* YYBACKUP */
  yych = YYPEEK;
  switch (yych) {
    case 0x00:
    case '=': goto yy113;
    case '\n':
    case '\r': goto yy154;
    case '}': goto yy166;
    default: goto yy185;
  }
yy187:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 0x00:
    case '\n':
    case '\r':
    case '=': goto yy154;
    case '\t':
    case ' ': goto yy187;
    case '#':
    case ':': goto yy169;
    case '$': goto yy189;
    case '\\': goto yy196;
    default: goto yy172;
  }
yy189:
  yyaccept = 3;
  YYSKIP;
  /* YYBACKUP */
  yych = YYPEEK;
  switch (yych) {
    case 0x00:
    case '\n':
    case '\r':
    case '=': goto yy63;
    case '#': goto yy169;
    case '$': goto yy197;
    case '(': goto yy198;
    case '{': goto yy200;
    default: goto yy172;
  }
yy190:
  yyaccept = 3;
  YYSKIP;
  /* YYBACKUP */
  yych = YYPEEK;
  switch (yych) {
    case 0x00: goto yy63;
    case '\n': goto yy115;
    case '\r': goto yy147;
    case '$': goto yy169;
    case '=': goto yy154;
    case '\\': goto yy202;
    default: goto yy172;
  }
yy191:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case '=': goto yy29;
    default: goto yy170;
  }
yy192:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 'E': goto yy203;
    default: goto yy20;
  }
yy193:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 'P': goto yy204;
    default: goto yy20;
  }
yy194:
  yyaccept = 3;
  YYSKIP;
  /* YYBACKUP */
  yych = YYPEEK;
  switch (yych) {
    case 0x00: goto yy46;
    case '\n': goto yy85;
    case '\r': goto yy130;
    case '$': goto yy169;
    case '%': goto yy172;
    case '=': goto yy154;
    default: goto yy166;
  }
yy195:
  yyaccept = 3;
  YYSKIP;
  /* YYBACKUP */
  yych = YYPEEK;
  switch (yych) {
    case 0x00:
    case '=': goto yy154;
    case '\t':
    case ' ': goto yy179;
    case '\n': goto yy85;
    case '\r': goto yy130;
    case '#':
    case ':': goto yy169;
    case '$': goto yy171;
    case '%': goto yy172;
    case '\\': goto yy181;
    default: goto yy166;
  }
yy196:
  yyaccept = 3;
  YYSKIP;
  /* YYBACKUP */
  yych = YYPEEK;
  switch (yych) {
    case 0x00: goto yy63;
    case '\n': goto yy115;
    case '\r': goto yy147;
    case '$': goto yy169;
    case '=': goto yy154;
    default: goto yy172;
  }
yy197:
  yyaccept = 3;
  YYSKIP;
  /* YYBACKUP */
  yych = YYPEEK;
  switch (yych) {
    case 0x00:
    case '\n':
    case '\r':
    case '=': goto yy63;
    case '#':
    case '$': goto yy169;
    case '(': goto yy198;
    case '{': goto yy200;
    default: goto yy172;
  }
yy198:
  yyaccept = 3;
  YYSKIP;
  /* YYBACKUP */
  yych = YYPEEK;
  switch (yych) {
    case 0x00:
    case '=': goto yy120;
    case '\n':
    case '\r': goto yy154;
    case ')': goto yy172;
    default: goto yy198;
  }
yy200:
  yyaccept = 3;
  YYSKIP;
  /* YYBACKUP */
  yych = YYPEEK;
  switch (yych) {
    case 0x00:
    case '=': goto yy122;
    case '\n':
    case '\r': goto yy154;
    case '}': goto yy172;
    default: goto yy200;
  }
yy202:
  yyaccept = 3;
  YYSKIP;
  /* YYBACKUP */
  yych = YYPEEK;
  switch (yych) {
    case 0x00:
    case '=': goto yy154;
    case '\t':
    case ' ': goto yy187;
    case '\n': goto yy115;
    case '\r': goto yy147;
    case '#':
    case ':': goto yy169;
    case '$': goto yy189;
    case '\\': goto yy190;
    default: goto yy172;
  }
yy203:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 'F': goto yy205;
    default: goto yy20;
  }
yy204:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 'A': goto yy206;
    default: goto yy20;
  }
yy205:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 'I': goto yy207;
    default: goto yy20;
  }
yy206:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 'N': goto yy208;
    default: goto yy20;
  }
yy207:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 'X': goto yy209;
    default: goto yy20;
  }
yy208:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 'S': goto yy210;
    default: goto yy20;
  }
yy209:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case '\t':
    case ' ': goto yy211;
    case '!':
    case '+':
    case '?': goto yy213;
    case ':': goto yy214;
    case '=': goto yy215;
    case '\\': goto yy217;
    default: goto yy20;
  }
yy210:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 'I': goto yy218;
    default: goto yy20;
  }
yy211:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 0x00:
    case '\n':
    case '\r':
    case '#': goto yy21;
    case '\t':
    case ' ': goto yy211;
    case '!':
    case '+':
    case '?': goto yy219;
    case '$': goto yy62;
    case '%': goto yy63;
    case ':': goto yy214;
    case '=': goto yy215;
    case '\\': goto yy220;
    default: goto yy46;
  }
yy213:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case '=': goto yy215;
    default: goto yy20;
  }
yy214:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case ':': goto yy221;
    case '=': goto yy215;
    default: goto yy28;
  }
yy215:
  YYSKIP;
#line 56 "src/lexer.re.c"
  { return RECIPEPREFIX_VAR;    }
#line 1876 "src/lexer.c"
yy217:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 0x00:
    case '#': goto yy46;
    case '\t':
    case ' ': goto yy48;
    case '\n': goto yy211;
    case '\r': goto yy222;
    case '$': goto yy49;
    case ':': goto yy68;
    case '\\': goto yy69;
    default: goto yy20;
  }
yy218:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 'O': goto yy223;
    default: goto yy20;
  }
yy219:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case '=': goto yy215;
    default: goto yy47;
  }
yy220:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case '\n': goto yy211;
    case '\r': goto yy222;
    case '$':
    case '=': goto yy21;
    case '%': goto yy63;
    default: goto yy46;
  }
yy221:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case '=': goto yy215;
    default: goto yy28;
  }
yy222:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case '\n': goto yy211;
    default: goto yy21;
  }
yy223:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 'N': goto yy224;
    default: goto yy20;
  }
yy224:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case '\t':
    case ' ': goto yy225;
    case '&': goto yy227;
    case ':': goto yy228;
    case '\\': goto yy230;
    default: goto yy20;
  }
yy225:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 0x00:
    case '\n':
    case '\r':
    case '#': goto yy21;
    case '\t':
    case ' ': goto yy225;
    case '!':
    case '+':
    case '?': goto yy233;
    case '$': goto yy234;
    case '%': goto yy235;
    case ':': goto yy228;
    case '=': goto yy29;
    case '\\': goto yy237;
    default: goto yy231;
  }
yy227:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case ':': goto yy228;
    default: goto yy20;
  }
yy228:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case ':': goto yy238;
    case '=': goto yy29;
    default: goto yy229;
  }
yy229:
#line 59 "src/lexer.re.c"
  { return SECONDEXPANSION_FN; }
#line 1987 "src/lexer.c"
yy230:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 0x00:
    case '#': goto yy46;
    case '\t':
    case ' ': goto yy48;
    case '\n': goto yy225;
    case '\r': goto yy239;
    case '$': goto yy49;
    case ':': goto yy68;
    case '\\': goto yy69;
    default: goto yy20;
  }
yy231:
  YYSKIP;
  yych = YYPEEK;
yy232:
  switch (yych) {
    case 0x00:
    case '\n':
    case '\r':
    case '#':
    case '=': goto yy21;
    case '\t':
    case ' ': goto yy240;
    case '$': goto yy234;
    case '%': goto yy235;
    case ':': goto yy242;
    case '\\': goto yy243;
    default: goto yy231;
  }
yy233:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case '=': goto yy29;
    default: goto yy232;
  }
yy234:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case '#': goto yy21;
    case '$': goto yy244;
    case '(': goto yy245;
    case '{': goto yy247;
    default: goto yy231;
  }
yy235:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 0x00:
    case '\n':
    case '\r':
    case '#':
    case '=': goto yy21;
    case '\t':
    case ' ': goto yy249;
    case '$': goto yy251;
    case ':': goto yy252;
    case '\\': goto yy254;
    default: goto yy235;
  }
yy237:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case '\n': goto yy225;
    case '\r': goto yy239;
    case '$':
    case '=': goto yy21;
    case '%': goto yy235;
    default: goto yy231;
  }
yy238:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case '=': goto yy29;
    default: goto yy229;
  }
yy239:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case '\n': goto yy225;
    default: goto yy21;
  }
yy240:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 0x00:
    case '\n':
    case '\r':
    case '#':
    case '=': goto yy21;
    case '\t':
    case ' ': goto yy240;
    case '$': goto yy234;
    case '%': goto yy235;
    case ':': goto yy242;
    case '\\': goto yy255;
    default: goto yy231;
  }
yy242:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case ':': goto yy256;
    default: goto yy229;
  }
yy243:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case '\n': goto yy240;
    case '\r': goto yy257;
    case '$':
    case '=': goto yy21;
    case '%': goto yy235;
    case ':': goto yy258;
    case '\\': goto yy259;
    default: goto yy231;
  }
yy244:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case '#':
    case '$': goto yy21;
    case '(': goto yy245;
    case '{': goto yy247;
    default: goto yy231;
  }
yy245:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case '\n':
    case '\r': goto yy21;
    case ')': goto yy231;
    default: goto yy245;
  }
yy247:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case '\n':
    case '\r': goto yy21;
    case '}': goto yy231;
    default: goto yy247;
  }
yy249:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 0x00:
    case '\n':
    case '\r':
    case '#':
    case '=': goto yy21;
    case '\t':
    case ' ': goto yy249;
    case '$': goto yy251;
    case ':': goto yy252;
    case '\\': goto yy260;
    default: goto yy235;
  }
yy251:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case '#': goto yy21;
    case '$': goto yy261;
    case '(': goto yy262;
    case '{': goto yy264;
    default: goto yy235;
  }
yy252:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case ':': goto yy266;
    default: goto yy253;
  }
yy253:
#line 60 "src/lexer.re.c"
  { return SECONDEXPANSION_PAT; }
#line 2180 "src/lexer.c"
yy254:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case '\n': goto yy249;
    case '\r': goto yy267;
    case '$':
    case '=': goto yy21;
    case ':': goto yy268;
    case '\\': goto yy269;
    default: goto yy235;
  }
yy255:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case '\n': goto yy240;
    case '\r': goto yy257;
    case '$':
    case '=': goto yy21;
    case '%': goto yy235;
    default: goto yy231;
  }
yy256:
  YYSKIP;
  goto yy229;
yy257:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case '\n': goto yy240;
    default: goto yy21;
  }
yy258:
  yyaccept = 4;
  YYSKIP;
  /* YYBACKUP */
  yych = YYPEEK;
  switch (yych) {
    case 0x00:
    case '\n':
    case '\r':
    case '#':
    case '=': goto yy229;
    case '\t':
    case ' ': goto yy240;
    case '$': goto yy234;
    case '%': goto yy235;
    case ':': goto yy242;
    case '\\': goto yy243;
    default: goto yy231;
  }
yy259:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 0x00:
    case '#':
    case '=': goto yy21;
    case '\t':
    case '\n':
    case ' ': goto yy240;
    case '\r': goto yy257;
    case '$': goto yy234;
    case '%': goto yy235;
    case ':': goto yy242;
    case '\\': goto yy243;
    default: goto yy231;
  }
yy260:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case '\n': goto yy249;
    case '\r': goto yy267;
    case '$':
    case '=': goto yy21;
    default: goto yy235;
  }
yy261:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case '#':
    case '$': goto yy21;
    case '(': goto yy262;
    case '{': goto yy264;
    default: goto yy235;
  }
yy262:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case '\n':
    case '\r': goto yy21;
    case ')': goto yy235;
    default: goto yy262;
  }
yy264:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case '\n':
    case '\r': goto yy21;
    case '}': goto yy235;
    default: goto yy264;
  }
yy266:
  YYSKIP;
  goto yy253;
yy267:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case '\n': goto yy249;
    default: goto yy21;
  }
yy268:
  yyaccept = 5;
  YYSKIP;
  /* YYBACKUP */
  yych = YYPEEK;
  switch (yych) {
    case 0x00:
    case '\n':
    case '\r':
    case '#':
    case '=': goto yy253;
    case '\t':
    case ' ': goto yy249;
    case '$': goto yy251;
    case ':': goto yy252;
    case '\\': goto yy254;
    default: goto yy235;
  }
yy269:
  YYSKIP;
  yych = YYPEEK;
  switch (yych) {
    case 0x00:
    case '#':
    case '=': goto yy21;
    case '\t':
    case '\n':
    case ' ': goto yy249;
    case '\r': goto yy267;
    case '$': goto yy251;
    case ':': goto yy252;
    case '\\': goto yy254;
    default: goto yy235;
  }
}
#line 64 "src/lexer.re.c"
}
